long = -IC:\mingw_dev_lib\include\SDL2 -LC:\mingw_dev_lib\lib -w -Wl,-subsystem,windows -lmingw32 -lSDL2main  C:\mingw_dev_lib\bin\SDL2.dll

default:
	g++ -g $(long) -I ../Math ../Math/vectormath.cpp test.cpp